import { Job, WorkType } from './models/jobs.model';

export const mockJobs: Job[] = [
  {
    id: 1,
    companyName: 'Google',
    companyLogo:
      'https://img.logo.dev/google.com?token=pk_dNiyapDZRpGK-JJJ-HN5wg&size=128&format=png&retina=true',
    expires: '2025-09-30',
    position: 'Software Engineer',
    startingSalary: 120000,
    workType: WorkType.HYBRID,
    location: 'Mountain View, CA',
    country: 'USA',
    qualifications: '3+ years in full-stack development, Python/Java, GCP',
    description:
      'Join the cloud infrastructure team building scalable backend systems.',
    isApplied: false,
    companyAddress: '1600 Amphitheatre Parkway, Mountain View, CA, USA',
    companyIndustry: 'Internet',
    companyWebsite: 'https://www.google.com',
  },
  {
    id: 2,
    companyName: 'Microsoft',
    companyLogo:
      'https://img.logo.dev/microsoft.com?token=pk_dNiyapDZRpGK-JJJ-HN5wg&size=128&format=png&retina=true',
    expires: '2025-10-05',
    position: 'Cloud Solutions Architect',
    startingSalary: 130000,
    workType: WorkType.REMOTE,
    location: 'Redmond, WA',
    country: 'USA',
    qualifications: 'Azure, Kubernetes, CI/CD pipelines',
    description: 'Design and deliver cloud-native solutions on Azure.',
    isApplied: false,
    companyAddress: 'One Microsoft Way, Redmond, WA, USA',
    companyIndustry: 'Software',
    companyWebsite: 'https://www.microsoft.com',
  },
  {
    id: 3,
    companyName: 'Apple',
    companyLogo:
      'https://img.logo.dev/apple.com?token=pk_dNiyapDZRpGK-JJJ-HN5wg&size=128&format=png&retina=true',
    expires: '2025-09-25',
    position: 'Hardware Engineer',
    startingSalary: 125000,
    workType: WorkType.ON_SITE,
    location: 'Cupertino, CA',
    country: 'USA',
    qualifications: 'Electronics design, PCB, RF systems',
    description: 'Work on next-gen consumer electronics hardware projects.',
    isApplied: false,
    companyAddress: '1 Apple Park Way, Cupertino, CA, USA',
    companyIndustry: 'Consumer Electronics',
    companyWebsite: 'https://www.apple.com',
  },
  {
    id: 4,
    companyName: 'Amazon',
    companyLogo:
      'https://img.logo.dev/amazon.com?token=pk_dNiyapDZRpGK-JJJ-HN5wg&size=128&format=png&retina=true',
    expires: '2025-10-10',
    position: 'Logistics Data Scientist',
    startingSalary: 110000,
    workType: WorkType.HYBRID,
    location: 'Seattle, WA',
    country: 'USA',
    qualifications: 'Python, ML, supply chain optimization',
    description: 'Analyze large datasets to optimize delivery networks.',
    isApplied: true,
    companyAddress: '410 Terry Ave N, Seattle, WA, USA',
    companyIndustry: 'E-commerce',
    companyWebsite: 'https://www.amazon.com',
  },
  {
    id: 5,
    companyName: 'Meta',
    companyLogo:
      'https://img.logo.dev/meta.com?token=pk_dNiyapDZRpGK-JJJ-HN5wg&size=128&format=png&retina=true',
    expires: '2025-11-01',
    position: 'AR/VR Developer',
    startingSalary: 140000,
    workType: WorkType.ON_SITE,
    location: 'Menlo Park, CA',
    country: 'USA',
    qualifications: 'Unity/Unreal, C++, immersive UX',
    description: 'Build next-generation augmented reality experiences.',
    isApplied: false,
    companyAddress: '1 Hacker Way, Menlo Park, CA, USA',
    companyIndustry: 'Social Media',
    companyWebsite: 'https://www.meta.com',
  },
  {
    id: 6,
    companyName: 'Adobe',
    companyLogo:
      'https://img.logo.dev/adobe.com?token=pk_dNiyapDZRpGK-JJJ-HN5wg&size=128&format=png&retina=true',
    expires: '2025-09-20',
    position: 'UX Designer',
    startingSalary: 90000,
    workType: WorkType.REMOTE,
    location: 'San Jose, CA',
    country: 'USA',
    qualifications: 'Figma, Adobe XD, user research',
    description: 'Design creative tools used by millions globally.',
    isApplied: false,
    companyAddress: '345 Park Avenue, San Jose, CA, USA',
    companyIndustry: 'Software',
    companyWebsite: 'https://www.adobe.com',
  },
  {
    id: 7,
    companyName: 'Intel',
    companyLogo:
      'https://img.logo.dev/intel.com?token=pk_dNiyapDZRpGK-JJJ-HN5wg&size=128&format=png&retina=true',
    expires: '2025-10-15',
    position: 'Firmware Engineer',
    startingSalary: 115000,
    workType: WorkType.HYBRID,
    location: 'Santa Clara, CA',
    country: 'USA',
    qualifications: 'C/C++, BIOS/UEFI, low-level systems',
    description: 'Develop firmware for next-gen processors.',
    isApplied: false,
    companyAddress: '2200 Mission College Blvd, Santa Clara, CA, USA',
    companyIndustry: 'Semiconductors',
    companyWebsite: 'https://www.intel.com',
  },
  {
    id: 8,
    companyName: 'Cisco',
    companyLogo:
      'https://img.logo.dev/cisco.com?token=pk_dNiyapDZRpGK-JJJ-HN5wg&size=128&format=png&retina=true',
    expires: '2025-10-30',
    position: 'Network Engineer',
    startingSalary: 105000,
    workType: WorkType.ON_SITE,
    location: 'San Jose, CA',
    country: 'USA',
    qualifications: 'Routing, switching, network protocols',
    description: 'Implement and manage enterprise network solutions.',
    isApplied: true,
    companyAddress: '170 West Tasman Drive, San Jose, CA, USA',
    companyIndustry: 'Networking',
    companyWebsite: 'https://www.cisco.com',
  },
  {
    id: 9,
    companyName: 'Tencent',
    companyLogo:
      'https://img.logo.dev/tencent.com?token=pk_dNiyapDZRpGK-JJJ-HN5wg&size=128&format=png&retina=true',
    expires: '2025-11-10',
    position: 'Mobile Game Dev',
    startingSalary: 95000,
    workType: WorkType.ON_SITE,
    location: 'Shenzhen',
    country: 'China',
    qualifications: 'Unity, C#, mobile monetization',
    description: 'Develop popular mobile games for global markets.',
    isApplied: false,
    companyAddress: 'Tencent Binhai Mansion, Nanshan District, Shenzhen, China',
    companyIndustry: 'Entertainment',
    companyWebsite: 'https://www.tencent.com',
  },
  {
    id: 10,
    companyName: 'Oracle',
    companyLogo:
      'https://img.logo.dev/oracle.com?token=pk_dNiyapDZRpGK-JJJ-HN5wg&size=128&format=png&retina=true',
    expires: '2025-09-28',
    position: 'Database Administrator',
    startingSalary: 115000,
    workType: WorkType.REMOTE,
    location: 'Redwood Shores, CA',
    country: 'USA',
    qualifications: 'Oracle DB, SQL, backup/recovery',
    description: 'Manage mission-critical enterprise databases.',
    isApplied: false,
    companyAddress: '500 Oracle Pkwy, Redwood Shores, CA, USA',
    companyIndustry: 'Software',
    companyWebsite: 'https://www.oracle.com',
  },
  {
    id: 11,
    companyName: 'IBM',
    companyLogo:
      'https://img.logo.dev/ibm.com?token=pk_dNiyapDZRpGK-JJJ-HN5wg&size=128&format=png&retina=true',
    expires: '2025-10-12',
    position: 'AI Researcher',
    startingSalary: 130000,
    workType: WorkType.ON_SITE,
    location: 'Armonk, NY',
    country: 'USA',
    qualifications: 'Deep learning, Python, research publications',
    description: 'Join IBM Research to push AI boundaries.',
    isApplied: false,
    companyAddress: '1 New Orchard Rd, Armonk, NY, USA',
    companyIndustry: 'Research',
    companyWebsite: 'https://www.ibm.com',
  },
  {
    id: 12,
    companyName: 'Salesforce',
    companyLogo:
      'https://img.logo.dev/salesforce.com?token=pk_dNiyapDZRpGK-JJJ-HN5wg&size=128&format=png&retina=true',
    expires: '2025-10-20',
    position: 'Sales Engineer',
    startingSalary: 100000,
    workType: WorkType.HYBRID,
    location: 'San Francisco, CA',
    country: 'USA',
    qualifications: 'CRM, SaaS, client-facing experience',
    description:
      'Support sales with technical expertise on Salesforce products.',
    isApplied: false,
    companyAddress: '415 Mission St, San Francisco, CA, USA',
    companyIndustry: 'CRM',
    companyWebsite: 'https://www.salesforce.com',
  },
  {
    id: 13,
    companyName: 'Tesla',
    companyLogo:
      'https://img.logo.dev/tesla.com?token=pk_dNiyapDZRpGK-JJJ-HN5wg&size=128&format=png&retina=true',
    expires: '2025-11-15',
    position: 'Autopilot Software Engineer',
    startingSalary: 150000,
    workType: WorkType.ON_SITE,
    location: 'Palo Alto, CA',
    country: 'USA',
    qualifications: 'C++, machine learning, ROS',
    description: 'Develop self-driving vehicle software systems.',
    isApplied: false,
    companyAddress: '3500 Deer Creek Rd, Palo Alto, CA, USA',
    companyIndustry: 'Automotive',
    companyWebsite: 'https://www.tesla.com',
  },
  {
    id: 14,
    companyName: 'Netflix',
    companyLogo:
      'https://img.logo.dev/netflix.com?token=pk_dNiyapDZRpGK-JJJ-HN5wg&size=128&format=png&retina=true',
    expires: '2025-09-22',
    position: 'Streaming Engineer',
    startingSalary: 125000,
    workType: WorkType.REMOTE,
    location: 'Los Gatos, CA',
    country: 'USA',
    qualifications: 'Video streaming, Go, scalable systems',
    description: 'Build backend systems for global video delivery.',
    isApplied: false,
    companyAddress: '100 Winchester Circle, Los Gatos, CA, USA',
    companyIndustry: 'Entertainment',
    companyWebsite: 'https://www.netflix.com',
  },
  {
    id: 15,
    companyName: 'Spotify',
    companyLogo:
      'https://img.logo.dev/spotify.com?token=pk_dNiyapDZRpGK-JJJ-HN5wg&size=128&format=png&retina=true',
    expires: '2025-10-07',
    position: 'Data Engineer',
    startingSalary: 110000,
    workType: WorkType.HYBRID,
    location: 'Stockholm',
    country: 'Sweden',
    qualifications: 'Kafka, Spark, Scala, music analytics',
    description: 'Enable data pipelines for music intelligence features.',
    isApplied: false,
    companyAddress: 'Regeringsgatan 19, Stockholm, Sweden',
    companyIndustry: 'Music Streaming',
    companyWebsite: 'https://www.spotify.com',
  },
  {
    id: 16,
    companyName: 'Airbnb',
    companyLogo:
      'https://img.logo.dev/airbnb.com?token=pk_dNiyapDZRpGK-JJJ-HN5wg&size=128&format=png&retina=true',
    expires: '2025-09-29',
    position: 'Backend Developer',
    startingSalary: 120000,
    workType: WorkType.REMOTE,
    location: 'San Francisco, CA',
    country: 'USA',
    qualifications: 'Ruby/Python, REST APIs, microservices',
    description: 'Work on features powering global accommodation services.',
    isApplied: false,
    companyAddress: '888 Brannan St, San Francisco, CA, USA',
    companyIndustry: 'Hospitality',
    companyWebsite: 'https://www.airbnb.com',
  },
  {
    id: 17,
    companyName: 'Dropbox',
    companyLogo:
      'https://img.logo.dev/dropbox.com?token=pk_dNiyapDZRpGK-JJJ-HN5wg&size=128&format=png&retina=true',
    expires: '2025-11-05',
    position: 'Storage Systems Engineer',
    startingSalary: 115000,
    workType: WorkType.HYBRID,
    location: 'San Francisco, CA',
    country: 'USA',
    qualifications: 'Distributed systems, Go, storage optimization',
    description: 'Scale file storage infrastructure for millions.',
    isApplied: false,
    companyAddress: '1800 Owens St, San Francisco, CA, USA',
    companyIndustry: 'Cloud Storage',
    companyWebsite: 'https://www.dropbox.com',
  },
  {
    id: 18,
    companyName: 'Uber',
    companyLogo:
      'https://img.logo.dev/uber.com?token=pk_dNiyapDZRpGK-JJJ-HN5wg&size=128&format=png&retina=true',
    expires: '2025-10-25',
    position: 'Logistics Optimization Engineer',
    startingSalary: 118000,
    workType: WorkType.ON_SITE,
    location: 'San Francisco, CA',
    country: 'USA',
    qualifications: 'Python, optimization algorithms, large-scale systems',
    description: 'Optimize ride matching and dispatch algorithms.',
    isApplied: true,
    companyAddress: '1455 Market St, San Francisco, CA, USA',
    companyIndustry: 'Ride-sharing',
    companyWebsite: 'https://www.uber.com',
  },
  {
    id: 19,
    companyName: 'Salesforce',
    companyLogo:
      'https://img.logo.dev/salesforce.com?token=pk_dNiyapDZRpGK-JJJ-HN5wg&size=128&format=png&retina=true',
    expires: '2025-11-20',
    position: 'Marketing Cloud Consultant',
    startingSalary: 95000,
    workType: WorkType.REMOTE,
    location: 'London',
    country: 'UK',
    qualifications:
      'Marketing automation, Salesforce platform, client interaction',
    description: 'Implement Salesforce Marketing Cloud for enterprise clients.',
    isApplied: false,
    companyAddress: 'The Campus, 4th Floor, 1 Pancras Square, London, UK',
    companyIndustry: 'CRM',
    companyWebsite: 'https://www.salesforce.com',
  },
  {
    id: 20,
    companyName: 'Intel',
    companyLogo:
      'https://img.logo.dev/intel.com?token=pk_dNiyapDZRpGK-JJJ-HN5wg&size=128&format=png&retina=true',
    expires: '2025-11-10',
    position: 'AI Accelerator Architect',
    startingSalary: 140000,
    workType: WorkType.ON_SITE,
    location: 'Haifa',
    country: 'Israel',
    qualifications: 'AI hardware, VHDL, chip design',
    description: 'Design next-gen AI accelerators for compute platforms.',
    isApplied: false,
    companyAddress: 'Haifa Research Labs, Intel, Israel',
    companyIndustry: 'Semiconductors',
    companyWebsite: 'https://www.intel.com',
  },
];
