--- UNION (WITHOUT DUPLICATES)
SELECT product_name
FROM sales_2023
UNION
SELECT product_name
FROM sales_2024;
--- WILL RETURN ALL UNIQUE PRODUCTS, WITHOUT DUPLICATES

--- UNION ALL WILL RETURN ALL VALUES, DUPLICATES TWICE
SELECT product_name
FROM sales_2023
UNION ALL
SELECT product_name
FROM sales_2024;

--- INTERSECT (COMMON PRODUCTS, WILL RETURN PRODUCTS THAT ARE COMMON FOR BOTH TABLES)
SELECT product_name
FROM sales_2023
INTERSECT
SELECT product_name
FROM sales_2024;

--- EXCEPT (PRODUCTS ONLY IN 2023)
SELECT product_name
FROM sales_2023
EXCEPT
SELECT product_name
FROM sales_2024;

--- 